#!/bin/bash
start(){
        echo "Starting JBoss WildFly 11..."
	su -l svc-jboss -c '/opt/liferay/wildfly-11.0.0.Final/bin/standalone.sh > /dev/null 2> /dev/null &'
}

stop(){
        echo "Stopping JBoss WildFly 11..."
        su -l svc-jboss -c '/opt/liferay/wildfly-11.0.0.Final/bin/jboss-cli.sh --connect command=:shutdown'
}

restart(){
	echo "Restarting JBoss WildFly 11..."
	connect=`ss -nat | grep 9990 | wc -l`
	if [ $connect -eq 0 ]
	then
		su -l svc-jboss -c '/opt/liferay/wildfly-11.0.0.Final/bin/standalone.sh > /dev/null 2> /dev/null &'
	else
	fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo "Use: {start|stop|restart}"
        exit 1
esac
exit 0
